
name: CI - Barbería Web

on: [push, pull_request]

jobs:
  validar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Ver estructura del proyecto
        run: ls -la

      - name: Validar HTML
        uses: Cyb3r-Jak3/html5validator-action@v0.4.0
