
name: CI - Barbería Web

on: [push, pull_request]

jobs:
  validar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Ver estructura del proyecto
        run: ls -la

      - name: Instalar dependencias
        run: npm install

      - name: Build del proyecto
        run: npm run build

      - name: Validar HTML en /dist
        uses: Cyb3r-Jak3/html5validator-action@v0.4.0
        with:
          directory: "./dist"

      - name: Run ESLint
        run: npx eslint src/ --ext .js,.jsx,.ts,.tsx

